name: Check Translations

on:
    pull_request:
        branches:
            - release/*

jobs:
    check_translations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Run script to check translations
              run: node check_translations.js
