name: Check Translations

on:
    pull_request:
        branches:
            - release2/*

jobs:
    check_translations:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Git status
              run: |
                  git status

            - name: Install dependencies
              run: npm install

            - name: Run script to check translations
              run: npm run translations
