name: Sync translations CI

on:
    pull_request:
        types:
            - closed
        branches:
            - "release/*"

jobs:
    sync_translations:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Run sync translation script
              run: node index.js

            - name: Check for changes and stop workflow if no changes
              run: |
                if git diff --quiet HEAD; then
                  echo "No files have changed. Skipping commit and push."
                else
                  echo "::set-output name=has_changes::true"
                fi

            - name: Add and commit changes to translation files
              if: needs.check_changes.outputs.has_changes == 'true'
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add result.json
                  git commit -m "Auto update - translation files"

            - name: Push changes
              if: needs.check_changes.outputs.has_changes == 'true'
              uses: ad-m/github-push-action@master
              with:
                  branch: ${{ github.ref }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
