name: Sync translations CI

on:
    pull_request:
        types:
            - closed
        branches:
            - "release/*"

jobs:
    sync_translations:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create sync branch
              run: |
                  sync_branch="sync-translation-${GITHUB_RUN_NUMBER}"
                  git checkout -b $sync_branch
                  git push origin $sync_branch
                  echo "sync_branch=$sync_branch" >> "$GITHUB_OUTPUT"

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Google artifact registry auth
              run: npm run registry-login

            - name: Install dependencies
              run: cd admin && npm ci

            - name: Run sync translation script
              env:
                  GSHEET_SERVICE_ACCOUNT_CRED: ${{ secrets.GSHEET_SERVICE_ACCOUNT_CRED }}
              run: cd admin && npm run sync:translations

            - name: Check for changes
              id: changes_check
              run: |
                  if git diff --quiet HEAD; then
                    echo "No files have changed"
                  else
                    echo "has_changes=true" >> "$GITHUB_ENV"
                    echo "Translation files are updated"
                  fi

            - name: Commit changes to translation files
              if: steps.changes_check.outputs.has_changes == 'true'
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add admin/src/i18n
                  git commit -m "Auto update - translation files"

            - name: Push changes
              if: steps.changes_check.outputs.has_changes == 'true'
              uses: ad-m/github-push-action@master
              with:
                  branch: ${{ steps.create_sync_branch.outputs.sync_branch }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Pull Request
              if: steps.changes_check.outputs.has_changes == 'true'
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ steps.create_sync_branch.outputs.sync_branch }}
                  title: "Sync Translation Changes"
                  body: "This pull request is automatically generated to sync translation changes."
                  labels: "auto-generated"
